Traceback (most recent call last):
  File "/Users/martinrinaldi/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/martinrinaldi/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/martinrinaldi/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/martinrinaldi/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/martinrinaldi/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/martinrinaldi/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/martinrinaldi/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/martinrinaldi/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
mdata = np.array(pd.read_excel('/Users/martinrinaldi/Dropbox/PhD in Finance/2022-2023/Term 2/Theoretical AP/LucasBonsai/DataEstimation.xlsx'))
mdata = mdata[mdata[:, 0] == mgrno]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/dz/0f0_0znd31d1839c60pzlvmw0000gn/T/ipykernel_64381/3617830016.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mmdata[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0mpd[0m[0;34m.[0m[0mread_excel[0m[0;34m([0m[0;34m'/Users/martinrinaldi/Dropbox/PhD in Finance/2022-2023/Term 2/Theoretical AP/LucasBonsai/DataEstimation.xlsx'[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mmdata[0m [0;34m=[0m [0mmdata[0m[0;34m[[0m[0mmdata[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m [0;36m0[0m[0;34m][0m [0;34m==[0m [0mmgrno[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'mgrno' is not defined
NameError: name 'mgrno' is not defined

